from django.urls import path, include
from rest_framework.routers import DefaultRouter
#DefaultRouter - auto generate urls for our viewset

from profiles_api import views

router = DefaultRouter()
#register specific viewset with our router
#1. url
#2. viewset
#3. base_name - optional - used to refer to the url in our code - 
# used to retrieve urls in our router
router.register('hello-viewset', views.HelloViewSet, basename='hello-viewset')
router.register('profile',views.UserProfileViewSet)
# no need to pass basename bcoz we have queryset in the viewset -> drf can figure out the name

urlpatterns = [
    path('hello-view/', views.HelloApiView.as_view()),
    path('',include(router.urls))
    #'': bcoz we don't wanna put any prefix in the url just base url
    #include(router.urls) -> include all the urls generated by the router
    #router.urls -> generate a list of urls for all the actions that are present in the viewset
    #as_view() -> convert api view class to be rendered by url
]